### ISSUE TITLE
Explain hardcoded values

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/sl-1-2-reflection-based-lidar-object-model#11]
**Describe the bug:**
Some values in the code are hardcoded due to missing OSI fields, e.g. wind speed and direction as well as a weather intensity sequence.
Some OSI fields exist now in the official standard for these values, but did not exist at the time or do not exist in the SL OSI. They need to be explained, so people are not confused.

**Comment by jdsika** [comment]
I am always in favor of having a dedicated file for this. Macro or singleton

**Comment by ClemensLinnhoff** [comment]
As this is a temporary solution until these values are part of the standard (and the enhancements from the SETlevel project are part of ASAM OSI), I would stick to explaining the values and why they are hardcoded. Then, once ASAM OSI has incorporated these values, make a clean switch to the standard.
